###
POST http://localhost:8080/student
Content-Type: application/json

{
  "id": 87,
  "name": "Piii",
  "surname": "ppp"
}

###
POST http://localhost:8080/student
Content-Type: application/json

{
  "id": 9,
"name": "Adilet",
"surname": "Orazgaliuly",
  "teacher": {
    "id": 0,
    "name": "Askar",
    "surname": "Bolat"
  }
}

###
GET http://localhost:8080/student
Accept: application/json

###
DELETE http://localhost:8080/student/0

###
PUT localhost:8080/student/3
Content-Type: application/json

{
  "name": "Hendalf",
  "surname": "Greate"
}

###
POST http://localhost:8080/teacher
Content-Type: application/json

{
  "id": 0,
  "name": "Askar",
  "surname": "Bolat"
}
###
POST http://localhost:8080/student/10
Content-Type: application/json

{
"id": 10,
"name": "abdu",
"surname": "kural",
  "teacher": {
    "id": 0,
    "name": "Askar",
    "surname": "Bolat"
  }
}
###
POST http://localhost:8080/student
Content-Type: application/json

{
"id": 11,
"name": "Torebek",
"surname": "Askerbek",
  "teacher": {
    "id": 0,
    "name": "Askar",
    "surname": "Bolat"
  }
}